let num1=document.getElementById("num1")
let num2=document.getElementById("num2")
let num3=document.getElementById("num3")
let num4=document.getElementById("num4")
let num5=document.getElementById("num5")
let num6=document.getElementById("num6")
let num7=document.getElementById("num7")
let num8=document.getElementById("num8")
let num9=document.getElementById("num9")

